name: Build/release

on:
  push:
    branches: [ master ]

jobs:
  release-win:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: NPM Install
        run: npm install

      - name: Distribute and Publish
        run: npm run distWin

      - name: View
        run: ls
