name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: see directory in electron_dist
      run: ls ./electron
    - name: electron mac os security identities
      run: security find-identity -v
    - name: Install dependencies
      run: npm install
    - name: Build on MacOS
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 0.0.2
      run: npm run build
    - name: Build Electron
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 0.0.2
      run: npm run distMac
    - name: see directory
      run: ls
    - name: see directory in electron_dist
      run: ls ./dist