name: Release
on:
  push:
    branches:
      - main
jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@master
        with:
          node-version: 20.14.0
      - name: run build
        run: npm run build:win
      - name: create release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          title: Release
