name: Release
on:
  push:
    branches:
      - main
jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: ./
      - name: Setup NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 20.14.0
      - name: Install Dependencies
        run: npm install
      - name: Build Setup
        run: npm run build:win
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'PeerShare-setup.exe'
